config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    root "users#index"
  end

  resources :users, only: [:index, :show] do
    resource :profile, only: [:new, :create, :show, :edit, :update]
    resources :posts, shallow: true do
      resources :likes, only: [:create, :destroy]
      resources :comments, except: [:show, :index] do
        resources :comments, only: [:new, :create]
        resources :likes, only: [:create, :destroy]
      end
    end
  end

  resources :friendships, only: [:create, :update, :destroy]
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :first_name, :last_name, presence: true

  def self.from_omniauth(user, auth)
    return if user.profile

    name = auth.info.name.split

    user.create_profile(
      first_name: name.first,
      last_name: name.last
    )
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def age
    return unless date_of_birth

    ((Time.zone.now - date_of_birth.to_time) / 1.year.seconds).floor
  end

  def incomplete?
    attributes.values.any?(&:nil?)
  end

  def required_info?
    [first_name, last_name].none?(&:blank?)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :fill_required_info, only: [:new, :create]
  before_action :set_user
  before_action :set_profile, except: [:new, :create]
  before_action -> { authorize @profile }, only: [:edit, :update]

  def new
    @profile = Profile.new
  end

  def create
    @profile = @user.create_profile(profile_params)

    if @profile.save
      UserMailer.welcome_email(@user).deliver_later
      redirect_to user_profile_path(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    if @profile.update(profile_params)
      redirect_to user_profile_path(@user)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :date_of_birth, :bio)
    end

    def set_user
      @user = current_user
    end

    def set_profile
      @profile = @user.profile
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with model: [user, profile], url: user_profile_path(user) do |f| %>
    <%= render "shared/form_errors", model: profile %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %>

    <%= f.label :date_of_birth %>
    <%= f.date_field :date_of_birth %>

    <%= f.label :bio %>
    <%= f.text_area :bio, data: { controller: "textarea-autogrow", action: "textarea-autogrow#autogrow" } %>

    <%= f.submit %>
<% end %>

<% if profile.required_info? %>
    <%= link_to "Edit later", users_path %>
<% end %>

app/views/profiles/edit.html.erb
<h1>Edit Your Profile</h1>

<%= render "form", user: @user, profile: @profile %>

app/views/profiles/new.html.erb
<h1>Create Your Profile</h1>

<%= render "form", user: @user, profile: @profile %>

app/views/profiles/show.html.erb
<h1>Your Profile</h1>

<ul>
    <li><strong>Full Name: </strong><%= @profile.full_name %></li>
    <% if @profile.age %>
        <li><strong>Age: <%= @profile.age %></strong></li>
    <% end %>
    <% unless @profile.bio.blank? %>
        <li><strong>Bio: </strong>
            <br><%= @profile.bio %>
        </li>      
    <% end %>
</ul>

<% if policy(@profile).update? %>
    <%= link_to "Edit Profile", edit_user_profile_path %>
<% end %>