config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    root "users#index"
  end

  resources :users, only: [:index, :show] do
    resource :profile, only: [:new, :create, :show, :edit, :update]
    resources :posts, shallow: true do
      resources :likes, only: [:create, :destroy]
      resources :comments, except: [:show, :index] do
        resources :comments, only: [:new, :create]
        resources :likes, only: [:create, :destroy]
      end
    end
  end

  resources :friendships, only: [:create, :update, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commenter, class_name: "User"
  belongs_to :commentable, polymorphic: true, counter_cache: true
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likable, dependent: :destroy

  validates :body, presence: true

  scope :latest_comments_by_post, lambda {
    latest_comments_ids = select("max(id)").where(commentable_type: "Post").group(:commentable_id)
    where(id: latest_comments_ids)
  }

  broadcasts_to ->(comment) { [comment.commentable, :comments] },
                target: ->(comment) { "#{comment.commentable_type.downcase}_#{comment.commentable.id}_comments" }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_commentable, except: :edit
  before_action -> { authorize @comment }, only: [:edit, :update, :destroy]

  def new
    @comment = Comment.new
  end

  def create
    @comment = @commentable.comments.build(comment_params)
    @comment.commenter = current_user

    if @comment.save
      respond_to do |format|
        format.html { redirect_back(fallback_location: root_path) }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      redirect_back(fallback_location: root_path)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_back(fallback_location: user_posts_path(current_user)) }
      format.turbo_stream
    end
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_commentable
      return @commentable = @comment.commentable if @comment

      # @commentable = GlobalID::Locator.locate(params[:commentable_gid])

      if params[:comment_id]
        @commentable = Comment.find(params[:comment_id])
      elsif params[:post_id]
        @commentable = Post.find(params[:post_id])
      end
    end

    def comment_params
      params.require(:comment).permit(:body, :commenter_id, :commentable_tye, :commentable_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= turbo_stream_from [comment, "comments"] %>

  <%= turbo_frame_tag comment do %>
    <div class="comment-wrapper">
      <div class="comment">
        <strong><%= link_to_feed(comment.commenter) %></strong>
        <p><%= comment.body %></p>
      </div>
    
      <%= dropdown button_text: "...", menu_position: "center" do %>
        <%= render "comments/creator_controls", comment: comment %>
      <% end %>
  </div>

  <%= turbo_frame_tag nested_dom_id(comment, "likes_counter") do %>
    <span><%= link_to "#{comment.likes.size} likes", "#" unless comment.likes.empty? %></span>
  <% end %>

  <div class="comment-actions">
    <%= render "shared/like_action", likable: comment, user: local_assigns[:user] %>
    <%= link_to "Reply", new_comment_comment_path(comment), data: { turbo_frame: nested_dom_id(comment, "new_comment") } %>
  </div>

    
  <ul>
    <%= turbo_frame_tag nested_dom_id(comment, "comments") do %>
      <% if local_assigns[:show_page] %>
          <%= render comment.comments, show_page: local_assigns[:show_page] %>
      <% else %>
        <%= link_to "See more replies",
              polymorphic_path(comment.commentable),
              data: { turbo_frame: "post-modal" } if comment.comments.size > 0 %>
      <% end %>
    <% end %>
    <%= turbo_frame_tag nested_dom_id(comment, "new_comment") %>
  </ul>
<% end %>

app/views/comments/_creator_controls.html.erb
<div class="comment__controls" data-visible-to="<%= comment.commenter_id %>">
    <%= link_to "Edit", edit_comment_path(comment) %>

    <%= button_to "Delete", comment, method: :delete, data: { turbo_confirm: "Are you sure?" } %>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [commentable, comment] do |form| %>
  <%= render "shared/form_errors", model: comment %>

  <div class="form-box">
    <%= form.text_area :body,
      autocomplete: "off",
      placeholder: "Write a comment...",
      data: { controller: "textarea-autogrow", action: "textarea-autogrow#autogrow" } %>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append nested_dom_id(@commentable, "comments"), @comment %>

<%= turbo_stream.update nested_dom_id(@commentable, "new_comment") do %>
    <%= render "form", comment: Comment.new, commentable: @commentable %>
<% end %>

<%= stream_counter_update model: @commentable, type: :comments %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove @comment %>

<%= stream_counter_update model: @commentable, type: :comments %>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>

<%= turbo_frame_tag @comment do %>
  <%= render "form", comment: @comment, commentable: nil %>
  <%= link_to "Cancel", :back %>
<% end %>

app/views/comments/new.html.erb
<h2>New comment</h2>

<%= turbo_frame_tag nested_dom_id(@commentable, "new_comment") do %>
  <%= render "form", comment: @comment, commentable: @commentable %>
<% end %>