config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    root "users#index"
  end

  resources :users, only: [:index, :show] do
    resource :profile, only: [:new, :create, :show, :edit, :update]
    resources :posts, shallow: true do
      resources :likes, only: [:create, :destroy]
      resources :comments, except: [:show, :index] do
        resources :comments, only: [:new, :create]
        resources :likes, only: [:create, :destroy]
      end
    end
  end

  resources :friendships, only: [:create, :update, :destroy]
end

app/views/shared/_form_errors.html.erb
<% if model.errors.any? %>
    <ul>
        <% model.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

app/views/shared/_like_action.html.erb
<%= turbo_frame_tag nested_dom_id(likable, "like_action") do %>
    <% if local_assigns[:user]  && user.likes?(likable) %>
        <%= button_to "Dislike", 
            like_path(Like.find_by(liker_id: user.id, likable: likable)),
            method: :delete %>
    <% else %>
        <%= button_to "Like", polymorphic_path([likable, :likes]), params: { likable_gid: likable.to_gid_param } %>
    <% end %>
<% end %>

app/views/shared/_request_response.html.erb
<span>
    <%= button_to "Accept", friendship_path(friendship), method: :patch, params: { friendship: { status: "accepted" } } %>
    <%= button_to "Decline", friendship_path(friendship), method: :delete, data: { turbo_confirm: "Are you sure?" }%>
</span>